// AUTO-GENERATED by scripts/build-project-assets.py — edit the source JSON, not this file.
import type { ProjectContent } from '@/components/ProjectDetail'

export const otherProjects: ProjectContent[] = [
  {
    "id": "vestella",
    "title": "베스텔라랩 인턴",
    "kicker": "Internship · Computer Vision",
    "period": "2023.09 — 2023.12",
    "role": "연구개발팀 인턴 · 데이터 라벨링, 모델 훈련, 추적 기반 주차 검증 방식 연구개발",
    "oneLiner": "YOLOv8 기반 주차장 CCTV 실시간 객체 탐지와, ByteTrack 추적 위에서 line counting·polygon detection과 주차 구역 관계식으로 이중주차 등 주차 상태를 유추·검증하는 방식을 연구·개발했습니다.",
    "stats": [
      {
        "value": "약 3.7개월",
        "label": "인턴 기간 (2023.09.01 ~ 2023.12.21)"
      },
      {
        "value": "2가지",
        "label": "추적 기반 주차 검증 방식 (line counting, polygon detection)"
      },
      {
        "value": "+0.2",
        "label": "기존 YOLOX 같은 모델 대비 평균 detection score"
      },
      {
        "value": "4 / 2 / 1 fps",
        "label": "서비스 가능 여부를 확인한 입력 프레임률"
      }
    ],
    "problem": "주차장 CCTV 영상에서 차량을 실시간으로 탐지하고 주차 여부를 검증해야 했습니다. 프레임률(fps)이 낮으면 추적기의 track id가 바뀌는 id switching 문제가 생겼습니다. 이중주차나 사각지대 차량은 detection을 누적해 확률로 판단하는 기존 방식으로는 파악하기 어려웠습니다. 낮은 fps에서도 안정적으로 동작하는 검증 방식이 필요했습니다.",
    "approach": [
      {
        "title": "라벨링 기준 설정",
        "body": "좌표를 찍을 때 너무 멀어서 사람 눈으로도 정확히 판단하기 어려운 객체는 라벨에서 제외했습니다. 이런 객체를 포함하면 모델이 '무조건 옳지 않다'고 학습해 정확도가 낮아진다고 판단했습니다."
      },
      {
        "title": "옵티마이저 변경",
        "body": "Adam은 momentum 때문에 loss가 최솟값을 지나쳐 후반에 다시 증가했습니다. SGD로 바꾸고 epoch를 늘려 loss가 천천히 줄어들도록 했습니다."
      },
      {
        "title": "재훈련 방식 비교",
        "body": "두 방식을 비교했습니다. 하나는 기존 훈련 모델에 새 데이터를 추가로 훈련하는 방식입니다. 다른 하나는 기본 YOLO 모델에 기존 데이터와 추가 데이터를 함께 훈련하는 방식입니다. 앞의 방식은 loss가 오르다 나중에 내려갔고, 뒤의 방식이 더 나은 결과를 보여 후자를 택했습니다."
      },
      {
        "title": "ByteTrack 인자 조정",
        "body": "ByteTrack의 인자(argument)를 조절해 최대한 넓게 객체를 추적하도록 맞췄습니다."
      },
      {
        "title": "가상 선 기반 line counting",
        "body": "track id switching을 피하려고 id에 의존하지 않는 방식을 택했습니다. 선으로 zone을 만들고 영역 내 차량 수를 비교합니다."
      },
      {
        "title": "polygon detection",
        "body": "특정 polygon 내부에서만 detection하는 방식을 두 번째 방법으로 사용했습니다. 이중주차와 사각지대 차량은 확률 누적 대신 zone 또는 polygon 안의 차량 수로 검증했습니다."
      },
      {
        "title": "주차 구역 관계식으로 이중주차 유추",
        "body": "주차 구역을 세부 구역으로 나누고, 각 구역과 이웃한 구역의 관계를 식으로 표현했습니다. ByteTrack이 내놓는 위치 변화 데이터를 이 식에 반영해 차량의 이동을 유추했습니다. 그 결과 큰 차량에 가려진(occlusion) 차량, 이중주차, 사각지역 차량처럼 탐지만으로는 판단하기 어려운 경우에도 위치와 상태를 추정할 수 있었습니다."
      },
      {
        "title": "fps 조건별 검증",
        "body": "입력 fps를 낮춰 가며 서비스 가능 범위를 확인했습니다. 4fps는 무조건 가능한 수준이었습니다. 2fps는 카메라 화각과 주차장 구조에 따라 원활하게 동작했습니다. 1fps는 floor change 구간 같은 경우에 사용할 수 있었습니다."
      }
    ],
    "architecture": "CCTV 영상\n  |\n  v\nYOLOv8 detection (직접 라벨링한 데이터로 훈련)\n  |\n  v\nByteTrack 추적 (인자 조정)\n  |\n  +--> line counting : 가상 선 zone 내 차량 수 비교\n  |\n  +--> polygon detection : 지정 polygon 내부만 detection\n  |\n  +--> 구역 관계식 : 구역-이웃 구역 관계 + 위치 변화로 이동 유추\n  |\n  v\n주차 여부 검증 (이중주차, 사각지대 포함)",
    "challenges": [
      {
        "problem": "Adam으로 훈련하면 후반에 loss가 다시 증가했습니다.",
        "cause": "momentum 때문에 loss가 최솟값을 지나쳤습니다.",
        "solution": "SGD로 바꾸고 epoch를 늘려 loss를 천천히 낮췄습니다."
      },
      {
        "problem": "기존 훈련 모델에 새 데이터를 추가 훈련하자 loss가 증가하다 나중에 내려갔습니다.",
        "solution": "기본 YOLO 모델에 기존 데이터와 추가 데이터를 함께 넣어 다시 훈련했습니다.",
        "result": "이 방식이 더 나은 결과를 보였습니다."
      },
      {
        "problem": "낮은 fps 영상에서 track id switching이 발생했습니다.",
        "solution": "id에 의존하지 않도록 가상 선 zone의 차량 수 비교와 polygon 내부 detection, 두 방식을 사용했습니다."
      },
      {
        "problem": "이중주차와 사각지대 차량은 detection 누적 확률 방식으로 파악하기 어려웠습니다.",
        "solution": "확률 대신 특정 zone 또는 polygon 안의 차량 수로 검증했습니다."
      }
    ],
    "results": [
      {
        "metric": "이중주차·가림·사각지역 차량",
        "after": "구역 관계식으로 위치·상태 유추",
        "condition": "ByteTrack 위치 변화 데이터를 구역 간 관계식에 반영"
      },
      {
        "metric": "평균 detection score",
        "after": "기존 YOLOX 같은 모델보다 0.2 높음",
        "condition": "같은 영상에서 비교. 세부 조건은 별도로 정리하지 않았습니다."
      },
      {
        "metric": "4fps",
        "after": "서비스 가능"
      },
      {
        "metric": "2fps",
        "after": "원활하게 동작",
        "condition": "카메라 화각과 주차장 구조에 따라 다름"
      },
      {
        "metric": "1fps",
        "after": "사용 가능",
        "condition": "floor change 구간 같은 경우"
      },
      {
        "metric": "구현 범위",
        "after": "라벨링, 훈련, 추적 기반 검증 2방식 연구개발"
      }
    ],
    "stack": [
      "YOLOv8",
      "ByteTrack",
      "YOLOX (비교)",
      "Adam / SGD"
    ],
    "lessons": [
      "모호한 데이터는 포함하기보다 제외하는 편이 모델 정확도에 유리할 수 있음을 확인했습니다.",
      "재훈련은 이어서 훈련하는 것보다 기본 모델에 전체 데이터를 다시 넣는 방식이 더 나았습니다.",
      "추적 id가 불안정한 조건에서는 id에 의존하지 않고 영역 내 차량 수를 세는 설계가 대안이 됩니다."
    ],
    "slides": [
      {
        "src": "/slides/vestella/p009.jpg",
        "caption": "베스텔라랩: 주차장 CCTV polygon/line 검출 화면과 성과(SGD 훈련, fps별 검증, 이중주차 대응) 정리"
      }
    ]
  },
  {
    "id": "kium",
    "title": "K-ium 의료 인공지능 공모전 · 뇌동맥류 진단 모델",
    "kicker": "Competition · Medical AI",
    "period": "2023.06 — 2023.08",
    "role": "뇌동맥류 진단 모델 개발 및 공모전 참가",
    "oneLiner": "뇌혈관조영술 영상으로 뇌동맥류의 발병 여부와 발병 부위를 진단하는 모델을 전이학습(Transfer Learning, EfficientNetB0)으로 개발해 우수상을 받은 공모전 프로젝트.",
    "stats": [
      {
        "value": "우수상",
        "label": "제2회 전국 대학(원)생 K-ium 의료인공지능 경진대회 (부산대학교병원 주최)"
      },
      {
        "value": "97%",
        "label": "발병 부위 분류 정확도 (Accuracy for locations 0.970, test)"
      },
      {
        "value": "0.607",
        "label": "발병 여부 AUROC (test, 부위 정확도와는 다른 지표)"
      },
      {
        "value": "54,096장",
        "label": "증강 후 전체 이미지 수 (원본 9,016장, 환자 1,127명)"
      }
    ],
    "problem": "주최 측은 익명화된 뇌혈관조영술 영상 2장(앞뒤/측면)과 뇌동맥류 여부·위치 CSV를 제공했다. 이를 이용해 뇌동맥류 여부와 발병 부위를 진단하는 AI 소프트웨어를 만드는 것이 과제였다. 평가는 C-statistics(AUROC) 기반 정확도의 정량평가와 결과 레포트의 정성평가로 이루어졌다. 학습 데이터는 환자 1,127명, 9,016장(환자당 8장)으로 딥러닝을 처음부터 학습하기에는 적었고, 컴퓨터 자원과 대회 기간도 제한적이었다.",
    "approach": [
      {
        "title": "데이터 구조 파악",
        "body": "9,016장은 환자당 8장(조영제 주입 위치와 촬영 각도별)으로 구성된다. train.csv에는 뇌동맥류 여부와 발견 위치가 0/1로 기록되어 있다. 이 라벨 구조를 기준으로 출력 형태를 설계했다."
      },
      {
        "title": "데이터 증식 (Data Augmentation)",
        "body": "좌우 반전, 회전, 이동, 전단(shear), 밝기 조절을 적용해 총 54,096장으로 늘렸다. 분할은 training 44,000 / validation 8,800 / test 1,296장이다. 목적은 적은 데이터에서 일반화 능력을 높이는 것이다."
      },
      {
        "title": "사전학습 모델 fine-tuning",
        "body": "자원과 기간 제약, 데이터 부족을 고려해 처음부터 학습하는 대신 기존 가중치를 fine-tuning했다. 백본(backbone)은 EfficientNetB0(입력 224x224x3, 출력 7x7x1280)이다. GlobalAveragePooling2D로 1280차원으로 줄인 뒤 Dense(21)로 score를 출력한다."
      },
      {
        "title": "과적합 점검 (Overfitting)",
        "body": "훈련 데이터가 적을수록 편향되기 쉽다. 여러 학습 결과를 비교하며 과적합 여부를 확인했다."
      },
      {
        "title": "평가",
        "body": "evaluate.py로 test 세트를 평가해 발병 부위 정확도와 발병 여부 AUROC를 산출했다."
      }
    ],
    "architecture": "뇌혈관조영술 영상 (224x224x3)\n  -> 증강 (flip / rotate / shift / shear / brightness)\n  -> EfficientNetB0 (pretrained, fine-tuning) : 7x7x1280\n  -> GlobalAveragePooling2D : 1280\n  -> Dense(21) : score\n  -> evaluate.py : AUROC / location accuracy",
    "challenges": [
      {
        "problem": "학습 데이터 부족과 과적합 위험",
        "solution": "사전학습 가중치 fine-tuning, 5종 이미지 증강, 여러 결과 비교를 통한 과적합 점검을 병행했다.",
        "result": "test에서 발병 부위 정확도 0.970, 발병 여부 AUROC 0.607을 기록했다."
      },
      {
        "problem": "모델별 최종 정확도 비교에만 집중해 영상 검열·전처리가 부족했음",
        "cause": "대회 후 주최 측에 요청해 최우수 수상작의 README를 읽어본 뒤, 이미지 검열과 전처리 과정이 부족했음을 깨달았다.",
        "solution": "정제된 데이터가 중요하다는 인사이트를 얻었고, 이후 모델 비교보다 데이터 정제를 먼저 보게 되었다.",
        "result": "우수상을 받았다. 발병 여부 지표는 개선 여지가 남았다."
      }
    ],
    "results": [
      {
        "metric": "발병 부위 정확도 (Accuracy for locations)",
        "after": "0.970 (약 97%)",
        "condition": "test 세트"
      },
      {
        "metric": "발병 여부 AUROC",
        "after": "0.607 (약 60%)",
        "condition": "test 세트"
      },
      {
        "metric": "데이터 규모",
        "after": "원본 9,016장 -> 증강 후 54,096장",
        "condition": "training 44,000 / validation 8,800 / test 1,296"
      },
      {
        "metric": "수상",
        "after": "우수상",
        "condition": "제2회 전국 대학(원)생 K-ium 의료인공지능 경진대회"
      }
    ],
    "stack": [
      "Python",
      "EfficientNetB0",
      "Transfer Learning",
      "Data Augmentation"
    ],
    "lessons": [
      "데이터가 적은 의료 영상에서는 전이학습과 증강이 현실적인 출발점이다. 다만 발병 여부 AUROC 0.607에서 보듯 그것만으로는 한계가 있다.",
      "모델 간 최종 정확도 비교보다 이미지 검열과 전처리 같은 데이터 정제가 중요하다는 점을 최우수 수상작을 보며 배웠다.",
      "서로 다른 과제(부위 분류 정확도, 여부 AUROC)는 지표를 구분해 보고해야 한다."
    ],
    "slides": [
      {
        "src": "/slides/kium/p010.jpg",
        "caption": "K-ium 대회 포스터, 데이터 분석·전처리·EfficientNetB0 모델 구성, 결과(AUROC 0.607 / 부위 정확도 97%)와 교훈"
      }
    ]
  },
  {
    "id": "ict",
    "title": "LPCDS: 번호판 위조 감지 시스템",
    "kicker": "Education · Vision AI · 충청권 ICT 이노베이션 스퀘어",
    "period": "2023.03 — 2023.07",
    "role": "딥러닝 영상처리 교육 과정(160H) · 데이터 수집·합성, 어노테이션, 번호판 탐지·OCR 담당",
    "oneLiner": "번호판이 블러 처리된 공개 차량 이미지의 한계를 랜덤 번호판 합성으로 풀고, YOLOv5 탐지와 Tesseract OCR로 차량 번호를 추출한 시스템.",
    "stats": [
      {
        "value": "160H",
        "label": "교육 과정 시간 (2023.03.04 ~ 2023.07.22)"
      },
      {
        "value": "26종",
        "label": "차종 분류 클래스 (브랜드+차명+연식)"
      },
      {
        "value": "40,000 : 8,000",
        "label": "차종 분류 Training : Validation 이미지 수"
      },
      {
        "value": "0.8827",
        "label": "차종 분류 val_accuracy (val_loss 0.8912)"
      }
    ],
    "problem": "공공 CCTV 등에서 차량 종류와 번호판을 함께 인식해 공공 데이터의 차종·번호판 정보와 대조하면, 대포차량 식별과 범죄 예방에 도움이 된다고 보고 LPCDS(License Plate Counterfeit Detection System)를 기획했다. 배경으로 2021년 총 절도 166,409건 중 5,550건이 오토바이·차량 절도였다는 경찰청 범죄통계, 2020년 기준 5년간 검거된 대포차가 3만여 대를 넘는다는 보도, 2022년 위조 번호판 밀수·유통 검거 사례를 제시했다. 기술적 과제는 국내 차량 이미지가 개인정보보호법 때문에 번호판이 블러 처리된 채로만 구해진다는 점이었다. 번호판 탐지·인식 모델을 학습시킬 원본 데이터가 없었다.",
    "approach": [
      {
        "title": "국내 차량 데이터 확보",
        "body": "국내 차량 분류가 목표라 해외 데이터 대신 AI-Hub의 국내 차량 이미지를 사용했다. 개인정보보호법에 따라 번호판이 블러된 이미지만 얻을 수 있었다."
      },
      {
        "title": "랜덤 번호판 합성으로 학습 데이터 생성",
        "body": "Python으로 랜덤 번호판 이미지를 자동 생성해 차량 이미지에 합성했다. 실제 번호판 이미지를 구할 수 없는 제약을 데이터 생성으로 우회했다."
      },
      {
        "title": "Roboflow 직접 어노테이션",
        "body": "합성 데이터셋을 Roboflow에서 직접 annotation하고, YOLOv5에서 쓸 수 있는 데이터셋으로 구성했다."
      },
      {
        "title": "YOLOv5 번호판 탐지",
        "body": "YOLOv5를 학습시키고 detect.py로 번호판 영역을 탐지했다. 번호판만 crop해 OCR 입력을 단순하게 만들었다."
      },
      {
        "title": "Tesseract OCR로 차량 번호 추출",
        "body": "crop된 번호판에 Tesseract를 적용해 문자열을 추출했다. 시연 예시 출력은 \"Plate Number: 112도 7147\"이다."
      },
      {
        "title": "차종 분류 모델 구성",
        "body": "AI-Hub의 차종/연식/번호판 인식용 영상을 정제(cleansing)해 브랜드+차명+연식 기준 26개 클래스를 선정했다. Image Generator로 64x64 입력의 자체 7층 모델을 학습했다. GPU 성능이 부족해 전이학습은 쓰지 않았다."
      }
    ],
    "architecture": "입력 차량 이미지\n   |\n   +--> [차종 분류: 자체 7층 모델, 64x64, 26 class]\n   |\n   +--> [YOLOv5 번호판 탐지] -> crop -> [Tesseract OCR]\n                                          |\n                                     번호 문자열\n   (차종 + 번호 -> 공공 데이터 대조: 기획 범위)\n\n학습 데이터: AI-Hub 국내 차량(번호판 블러)\n           + Python 랜덤 번호판 합성 + Roboflow 어노테이션",
    "challenges": [
      {
        "problem": "번호판이 블러된 이미지만 확보할 수 있어 번호판 탐지·OCR 학습 데이터가 없었다.",
        "cause": "개인정보보호법 때문에 국내 차량 이미지의 번호판이 블러 처리되어 있었다.",
        "solution": "Python으로 랜덤 번호판 이미지를 자동 생성해 차량 이미지에 합성하고, 학습용 데이터셋을 직접 구축했다."
      },
      {
        "problem": "GPU 성능이 부족해 전이학습(transfer learning)을 쓰기 어려웠다.",
        "solution": "전이학습 대신 64x64 입력의 자체 7층 모델로 26종 차종 분류를 학습했다.",
        "result": "val_loss 0.8912, val_accuracy 0.8827. 학습 그래프에서는 epoch이 진행될수록 val_loss가 올라가는 과적합(overfitting) 경향이 보인다."
      }
    ],
    "results": [
      {
        "metric": "차종 분류 val_accuracy",
        "after": "0.8827",
        "condition": "26 클래스, Training 40,000 : Validation 8,000, 자체 7층 모델(64x64)"
      },
      {
        "metric": "차종 분류 val_loss",
        "after": "0.8912",
        "condition": "위와 동일"
      },
      {
        "metric": "번호판 탐지·OCR 정량 성능",
        "after": "수치 없음",
        "condition": "정량 평가는 하지 않았고, 시연 예시 출력만 있다"
      },
      {
        "metric": "구현 범위",
        "after": "데이터 합성 → Roboflow 어노테이션 → YOLOv5 탐지·crop → Tesseract OCR, 별도 차종 분류 모델",
        "condition": "공공 데이터 대조는 기획 범위"
      }
    ],
    "stack": [
      "Python",
      "AI-Hub",
      "Roboflow",
      "YOLOv5",
      "Tesseract OCR",
      "Image Generator",
      "자체 7층 모델 (64x64)"
    ],
    "lessons": [
      "개인정보 보호로 원본 데이터가 제한될 때, 합성 데이터 생성으로 학습 데이터의 공백을 메울 수 있었다.",
      "GPU 자원이 부족하면 전이학습 대신 작은 자체 모델을 택하게 된다. 이때 val_loss 상승 같은 과적합 신호도 함께 점검해야 한다."
    ],
    "pdf": {
      "href": "/pdfs/ict.pdf",
      "label": "ICT 교육 프로젝트 자료",
      "pages": 5
    },
    "slides": [
      {
        "src": "/slides/ict/p171.jpg",
        "caption": "LPCDS(번호판 위조 감지 시스템) 프로젝트 표지"
      },
      {
        "src": "/slides/ict/p174.jpg",
        "caption": "차종분류 자체 모델: 26종, 40,000:8,000, val_accuracy 0.8827 및 학습 곡선"
      }
    ]
  },
  {
    "id": "astel",
    "title": "아스텔 X-ray rewindowing",
    "kicker": "Research · Medical Imaging",
    "period": "2022.12 — 2023.01",
    "role": "2인 팀 · Raw→DICOM 변환, 이상치 제거, GMM 기반 width/level 도출 파이프라인 구현",
    "oneLiner": "GMM(Gaussian Mixture Model)으로 X-ray 영상의 픽셀 분포를 모델링해 window width/level을 자동으로 도출하고, DICOM에 반영하는 파이프라인을 구현했습니다.",
    "stats": [
      {
        "value": "4주",
        "label": "협력 학부연구생 프로젝트 기간"
      },
      {
        "value": "4",
        "label": "GMM n_components (왼쪽 2개를 window 산출에 사용)"
      },
      {
        "value": "3가지",
        "label": "EM max_iter 비교 조건 (1 / 500 / 2000)"
      },
      {
        "value": "2",
        "label": "z-score 이상치 제거 threshold"
      }
    ],
    "problem": "입력 X-ray 이미지에 수학적 알고리즘을 적용해, 재현성 있고 일관된 영상 표현을 만드는 적절한 파라미터 설정 방법을 제안하는 것이 목표였습니다. 영상의 픽셀 분포(히스토그램)에서 window width/level을 자동으로 구하는 과제입니다.",
    "approach": [
      {
        "title": "Raw → DICOM 표준화",
        "body": "MATLAB의 raw_to_dicom.m에서 내장 dicomwrite로 Raw 데이터를 DICOM으로 변환했습니다. 이후 Python(pydicom)으로 pixel_array와 최소/최대 픽셀값 메타데이터를 읽었습니다."
      },
      {
        "title": "관측 오류값 제거",
        "body": "히스토그램 맨 앞 구간의 이상값을 제거했습니다. 이어서 z-score(Z=(x-μ)/σ) 기준 threshold=2, 즉 평균 ±표준편차×2 구간의 값만 사용했습니다. 제거 전후 히스토그램을 비교했습니다."
      },
      {
        "title": "GMM으로 분포 모델링",
        "body": "scikit-learn GaussianMixture(n_components=4)와 EM 알고리즘으로 각 성분의 평균·분산을 반복 추정했습니다. 여러 봉우리로 이뤄진 히스토그램을 혼합 분포로 표현하는 접근입니다."
      },
      {
        "title": "반복 횟수 비교",
        "body": "max_iter를 1, 500, 2000으로 바꿔 적합 결과를 비교했습니다. 반복이 늘수록 평균·분산에 더 가깝게 근사되었습니다."
      },
      {
        "title": "Width / Level 도출",
        "body": "4개 가우시안 중 왼쪽 2개(주황, 빨강)를 선택했습니다. Width는 주황 표준편차×3, 두 중심값의 차, 빨강 표준편차×3의 합입니다. Level은 가장 작은 x값 + width/2로 계산했습니다."
      },
      {
        "title": "적용과 검증",
        "body": "show_dcm.m의 대비 조정 창에 width, level을 적용해 히스토그램 영역을 추출하고 원본과 결과 이미지를 비교했습니다. 마지막으로 pydicom으로 WindowCenter=level, WindowWidth=width를 설정해 DICOM 파일로 저장했습니다."
      }
    ],
    "architecture": "raw data\n  |  raw_to_dicom.m (MATLAB dicomwrite)\n  v\nDICOM image\n  |  dicom_to_array (pydicom pixel_array)\n  v\narray data\n  |  drop first histogram bin -> remove observation errors\n  |  find_outlier_z (threshold=2)\n  v\nGaussianMixture (n_components=4, EM)\n  |  left 2 components -> width, level\n  v\nshow_dcm.m contrast window / GMM_dicom.dcm\n  (WindowCenter=level, WindowWidth=width)",
    "challenges": [
      {
        "problem": "히스토그램 맨 앞 구간의 관측 오류값이 있었습니다.",
        "solution": "맨 앞 구간을 제거하고 z-score(threshold=2) 이상치 제거를 적용한 뒤 전후 히스토그램을 비교했습니다."
      },
      {
        "problem": "EM 반복 횟수에 따라 평균·분산 추정 정확도가 달라졌습니다.",
        "solution": "max_iter를 1, 500, 2000으로 비교해 반복이 늘수록 더 근접함을 확인했습니다."
      }
    ],
    "results": [
      {
        "metric": "파이프라인 구현 범위",
        "after": "Raw→DICOM 변환, 이상치 제거, GMM 적합, width/level 산출, 대비 창 적용, DICOM 저장까지 end-to-end"
      },
      {
        "metric": "결과 출력 방식",
        "after": "WindowCenter/WindowWidth를 설정한 DICOM 파일 저장"
      },
      {
        "metric": "max_iter 비교",
        "before": "max_iter=1",
        "after": "max_iter=500 / 2000",
        "condition": "반복이 늘수록 평균·분산에 더 근접 (정성 관찰)"
      },
      {
        "metric": "정량 성과 지표",
        "after": "없음",
        "condition": "원본과 출력 이미지의 정성 비교만 수행"
      }
    ],
    "stack": [
      "MATLAB",
      "Python",
      "pydicom",
      "numpy",
      "scikit-learn (GaussianMixture)",
      "DICOM"
    ],
    "lessons": [
      "실측 히스토그램에는 관측 오류값이 섞일 수 있어, 모델링 전에 이상치 처리 단계가 필요했습니다.",
      "EM 기반 GMM은 반복 횟수 설정이 추정 결과에 영향을 주므로 조건별 비교가 필요했습니다."
    ],
    "pdf": {
      "href": "/pdfs/astel.pdf",
      "label": "X-ray rewindowing 자료",
      "pages": 14
    },
    "slides": [
      {
        "src": "/slides/astel/p182.jpg",
        "caption": "Raw -> DICOM -> 배열 -> 이상치 제거 -> GMM -> width/level 적용까지의 전체 파이프라인 블록도"
      },
      {
        "src": "/slides/astel/p186.jpg",
        "caption": "z-score 이상치 제거(threshold=2) 코드와 전후 히스토그램"
      },
      {
        "src": "/slides/astel/p188.jpg",
        "caption": "GMM EM max_iter 1/500/2000 비교"
      },
      {
        "src": "/slides/astel/p189.jpg",
        "caption": "4개 가우시안 중 왼쪽 2개로 width, level 산출 방식"
      },
      {
        "src": "/slides/astel/p190.jpg",
        "caption": "산출 width/level을 대비 조정 창에 적용"
      },
      {
        "src": "/slides/astel/p191.jpg",
        "caption": "DICOM 원본 대비 최종 출력 결과 이미지"
      }
    ]
  }
]
