// AUTO-GENERATED by scripts/build-project-assets.py — edit the source JSON, not this file.
import type { ProjectContent } from '@/components/ProjectDetail'

export const ssafyProjects: ProjectContent[] = [
  {
    "id": "odab",
    "title": "O!dAb (O! 답)",
    "kicker": "SSAFY · RAG Math Tutor",
    "period": "2025.04 — 2025.05",
    "role": "AI 개발 (6인 팀) · RAG 시스템, 유사 문제 추천, Sequential Thinking 풀이 설계",
    "oneLiner": "RAG와 Sequential Thinking 툴 콜링으로, 정답이 아니라 개념·접근법·단계별 풀이를 알려주는 태블릿 수학 학습 서비스.",
    "stats": [
      {
        "value": "약 5주",
        "label": "프로젝트 기간 (2025.04.14 ~ 05.22)"
      },
      {
        "value": "6인",
        "label": "팀 규모"
      },
      {
        "value": "9개",
        "label": "sequentialThinking 툴 파라미터 수"
      },
      {
        "value": "0.2",
        "label": "유사 문제 채택 유사도 임계값"
      }
    ],
    "problem": "범용 LLM은 고난이도 수학 문제에서 완전한 풀이를 내지 못하는 경우가 있고, 사고 과정보다 정답 위주로 답합니다. 학습자는 문제마다 \"접근법을 알려줘\", \"어떤 개념을 써야 해?\"를 매번 다시 프롬프트해야 했고, 개인별 약점도 파악되지 않았습니다. O!dAb은 문제 이미지를 올리면 개념, 접근법, 단계, 정답을 일관된 구조로 제공하는 것을 목표로 했습니다. 제 역할은 풀이 품질을 좌우하는 RAG 검색, 유사 문제 추천, 단계별 사고 구조를 설계하는 것이었습니다.",
    "approach": [
      {
        "title": "프롬프트 반복을 파이프라인으로 대체",
        "body": "사용자가 매번 입력하던 추가 질문(접근법, 개념, 단계 분리)을 서비스가 대신 수행하도록 했습니다. 이미지 입력, 텍스트 추출, 풀이 생성, 개념 연결 순서로 흐름을 고정했습니다."
      },
      {
        "title": "RAG로 유사 문제와 풀이를 참고자료로 주입",
        "body": "문제 텍스트를 BAAI/bge-m3로 임베딩하고 FAISS(IndexFlatL2)에서 가장 가까운 1건을 검색합니다. 유사도는 1/(1+L2 거리)로 환산하며 0.2 이상일 때만 채택합니다. 미달이면 참고 없이 진행해, 무관한 예시가 프롬프트를 오염시키는 것을 막았습니다."
      },
      {
        "title": "Prompt Composer로 참고 문제와 풀이 단계 조합",
        "body": "검색된 question_id로 DB에서 참고 문제와 단계별 풀이를 조회합니다. 이를 \"참고 문제 / 풀이 step N\" 형태로 프롬프트에 덧붙여 Claude를 호출합니다. 벡터 검색은 별도 Python(FastAPI) 서버로 분리하고, Spring Boot 서버가 이를 호출합니다."
      },
      {
        "title": "Sequential Thinking을 툴 콜링(Tool Calling)으로 구현",
        "body": "Claude Messages API에 sequentialThinking 툴을 등록했습니다. 파라미터는 thought, nextThoughtNeeded, thoughtNumber, totalThoughts와 수정·분기 관련 값입니다. 모델이 추가 사고가 필요하다고 답하는 동안 재귀 호출합니다. 최대 깊이 20, 메시지 40개 초과 시 오류, 타임아웃 30초, 재시도 3회로 무한 루프와 비용 폭주를 제한했습니다."
      },
      {
        "title": "구조화된 결과로 학습 기능과 연결",
        "body": "사고가 끝나면 요약 프롬프트로 question, steps(10단계 이내), answer, concept을 JSON으로 생성해 저장합니다. 개념은 등록된 세부 개념 목록에서 최대 5개를 고르게 해 개념 학습, 오답노트와 연결했습니다."
      },
      {
        "title": "정답 판정과 문제 수정 호출 분리",
        "body": "이미지에서 텍스트를 추출하는 호출, 정답 일치를 엄격한 기준으로 판정하는 호출, 인식 오류를 고치는 호출을 풀이 생성과 분리했습니다."
      }
    ],
    "architecture": "[Next.js 프런트]\n      |\n[Spring Boot] --이미지--> Claude(텍스트 추출)\n      |\n      +--문제 텍스트--> [FastAPI + FAISS (bge-m3)]\n      |                    유사도 >= 0.2 이면 question_id\n      +--DB 조회--> 참고 문제 + 풀이 step (MySQL)\n      |\n      +--Prompt 조합--> Claude + sequentialThinking 툴\n      |                    (nextThoughtNeeded 동안 재귀, 깊이 20)\n      +--요약 프롬프트--> JSON {question, steps, answer, concept}\n      |\n   MySQL / Redis 저장 -> 개념 학습 / 오답노트",
    "results": [
      {
        "metric": "구현 범위",
        "after": "이미지 문제 인식, RAG 유사 문제 검색, Sequential Thinking 단계별 풀이, 개념 연결, 개인 맞춤 오답노트, 태블릿 펜 메모 기능까지 서비스 흐름을 구현했습니다."
      },
      {
        "metric": "RAG 파이프라인",
        "after": "bge-m3 임베딩, FAISS 인덱스, FastAPI 검색 엔드포인트, Spring Boot 프롬프트 조합까지 연결했습니다."
      },
      {
        "metric": "사고 루프 안전장치",
        "after": "재귀 깊이 20, 메시지 40개, 타임아웃 30초, 재시도 3회, 풀이 단계 10개 이내."
      },
      {
        "metric": "배포 방식",
        "after": "AWS EC2 위 Docker 구성. 카나리 배포(트래픽 10%에서 100%까지 단계 확대, 자동 롤백)를 설계도로 제시했습니다. 인프라는 다른 팀원이 담당했습니다."
      },
      {
        "metric": "정확도·성능 평가",
        "after": "정량 수치는 측정하지 않았습니다."
      }
    ],
    "lessons": [
      "LLM 툴 콜링을 루프에 쓸 때는 깊이, 메시지 수, 타임아웃, 재시도 같은 종료 조건을 먼저 설계해야 합니다.",
      "RAG는 검색 결과를 무조건 붙이지 말고 유사도 임계값으로 걸러야 합니다. 다만 임계값 0.2는 평가 데이터로 검증하지 못했고, 이는 남은 과제입니다.",
      "벡터 검색을 별도 서비스로 분리하면 임베딩 모델과 인덱스를 백엔드와 독립적으로 바꿀 수 있습니다."
    ],
    "pdf": {
      "href": "/pdfs/odab.pdf",
      "label": "O!dAb 발표 자료",
      "pages": 19
    },
    "slides": [
      {
        "src": "/slides/odab/p018.jpg",
        "caption": "기획 배경: 정답 위주 답변과 반복 프롬프팅의 불편함(3가지 문제 정의)"
      },
      {
        "src": "/slides/odab/p020.jpg",
        "caption": "기능 시연: sequentialthinking 툴 호출을 거친 단계별 풀이 화면"
      },
      {
        "src": "/slides/odab/p024.jpg",
        "caption": "Sequential thinking 툴 콜링 파라미터(next_thought_needed 등)"
      },
      {
        "src": "/slides/odab/p026.jpg",
        "caption": "RAG 흐름: 문제 -> bge-m3 임베딩 -> 유사도 검색 -> 프롬프트에 추가"
      },
      {
        "src": "/slides/odab/p028.jpg",
        "caption": "카나리 배포 5단계 프로세스"
      },
      {
        "src": "/slides/odab/p029.jpg",
        "caption": "서비스 아키텍처: Nginx 트래픽 비율 제어 기반 stable/canary 이중 환경, Jenkins, MySQL/Redis"
      },
      {
        "src": "/slides/odab/p031.jpg",
        "caption": "기대효과: 접근성, 확대성, 논리성"
      }
    ]
  },
  {
    "id": "yoohoo",
    "title": "YooHoo",
    "kicker": "SSAFY · Fintech",
    "period": "2025.03 — 2025.04",
    "role": "Back-End — 금융 도메인 모델링, 금융 API 연동, Redis 캐싱, 수입·지출 예측, 신뢰지수",
    "oneLiner": "SSAFY 금융 API로 유기견 후원 단체의 후원금 입출금·카드 거래를 조회해 후원자에게 투명하게 공개하는 서비스",
    "stats": [
      {
        "value": "19일",
        "label": "개발 기간 (2025.03.24 ~ 04.11)"
      },
      {
        "value": "7개",
        "label": "JPA 엔티티 (User, Shelter, Dog, Donation, Withdrawal, MerchantCategory, File)"
      },
      {
        "value": "약 3,700줄",
        "label": "백엔드 controller/service/entity 소스 규모 (Spring Boot)"
      },
      {
        "value": "3가지",
        "label": "신뢰지수 산정 기준 (100점 만점)"
      },
      {
        "value": "6인",
        "label": "팀 구성 (Front 3 · Back 2 · Infra 1)"
      }
    ],
    "problem": "유기견 후원 단체의 기부금 오남용 보도가 이어지면서, 후원자는 어떤 단체를 믿고 후원할지 판단하기 어렵다. 기부 요청 시설을 믿을 수 없어 기부하지 않는다는 응답이 61.5%로 나타난 조사도 있었다. 기존 단체는 입출금 내역을 엑셀로만 제공해 후원자가 사용 내역을 한눈에 보기 어렵고, 단체도 사용 내역 분류와 영수증 증빙 관리에 부담이 크다. 이 프로젝트는 은행(SSAFY 금융 API) 거래 데이터를 그대로 연결해 후원금 흐름을 자동 분류·공개하고, 단체 선택 지표와 수입·지출 예측까지 제공하는 것을 목표로 했다.",
    "approach": [
      {
        "title": "금융 도메인 모델링과 ERD 설계",
        "body": "Donation, Withdrawal, MerchantCategory, File, Shelter, Dog, User 7개 엔티티로 후원 입금과 출금을 모델링했다. Withdrawal에 transactionUniqueNo(unique)를 두어 MySQL 레코드와 은행 거래를 1:1로 연결했다. 이 값이 거래 투명성(매출전표 확인)의 기준 키다."
      },
      {
        "title": "SSAFY 금융 API 연동",
        "body": "계좌목록 조회, 카드 가입목록 조회, 회원 userKey 조회를 FinanceService, BankbookService, CardService 등으로 나누어 연동했다. API 공통 헤더(apiName, 전송일시, 기관 거래고유번호=일시+난수 6자리)는 직접 생성했다."
      },
      {
        "title": "Redis 기반 금융정보 캐싱",
        "body": "userKey, 계좌번호, 카드번호를 Redis에 보관해 매 요청마다 금융 정보를 다시 조회하지 않도록 했다. 단체 금융정보는 TTL 1시간으로 두었다. 지출 내역 요청은 Spring, Redis, 금융 API 조회 순서로 흐른다."
      },
      {
        "title": "멱등한 출금 동기화 (Idempotent Sync)",
        "body": "/api/withdrawal/sync로 계좌 출금(카테고리 \"인건비\")과 카드 거래(MerchantCategory로 가맹점 업종 매핑)를 일괄 반영한다. transactionUniqueNo가 이미 있으면 저장을 건너뛰어, 반복 동기화해도 중복이 생기지 않는다."
      },
      {
        "title": "지수평활법 수입·지출 예측",
        "body": "최근 6주 주간 합계에 alpha=0.3 단순 지수평활(Exponential Smoothing)을 적용해 5주치 예측값을 반환한다. 최근 후원에 더 높은 가중치를 주고, 노이즈에 강하며, 계산이 단순해 빠르다는 점이 선택 이유다. 프론트 차트에서는 예측값을 별도 색 막대로 표시한다."
      },
      {
        "title": "단체 신뢰지수 (Reliability Index)",
        "body": "100점 만점으로 계산한다. 강아지 관련 지출 비율 50점, 영수증(활동자료) 첨부 출금 비율 30점, 설립 연차(연 2점, 최대 20점) 20점이다. 후원자가 단체를 고르는 지표로 제공한다."
      },
      {
        "title": "API와 증빙 파일 처리",
        "body": "/api/shelter, /api/donations, /api/withdrawal, /api/bankbook, /api/card 등 엔드포인트를 구성했고 카카오 로그인을 붙였다. 영수증 등 증빙 파일은 AWS S3에 업로드하고 출금 내역에 연결한다."
      }
    ],
    "architecture": "사용자(PWA)\n   |\nNginx (Docker, EC2) + Let's Encrypt\n   |-- Next.js 프론트 (EC2 x2, stable/canary)\n   `-- Spring Boot 백엔드 (EC2 x2)\n          |-- MySQL (거래 · 후원 · 단체)\n          |-- Redis (userKey/계좌/카드, TTL 1h)\n          |-- SSAFY 금융 API (계좌/카드 거래)\n          `-- AWS S3 (영수증 등 증빙)\nCI/CD: GitLab -> Jenkins -> Docker Hub",
    "results": [
      {
        "metric": "구현 완료 범위",
        "after": "후원금 운용내역 요약, 카테고리별 지출 비율, 후원/사용내역 자동 분류, 증빙 첨부, 신뢰지수, 수입·지출 예측 기능이 구현된 백엔드와 화면(메인/로그인, 단체 보기, 후원하기, 마이페이지, 관리자)"
      },
      {
        "metric": "차별점 3가지",
        "after": "금융 DB 조회를 통한 투명성 확보, 후원 단체 선택 지표(신뢰지수), 후원금 수입·지출 예측"
      },
      {
        "metric": "데이터 정합성",
        "after": "transactionUniqueNo unique 제약과 존재 확인으로 반복 동기화 시 중복 저장 방지"
      },
      {
        "metric": "배포 방식",
        "after": "Docker, Jenkins CI/CD, Nginx 카나리/스테이블 구성 (인프라는 팀원 담당)"
      },
      {
        "metric": "정량 성과 지표",
        "after": "측정된 성과 수치는 없다. 발표 화면의 금액·퍼센트는 시연용 예시 데이터다."
      }
    ],
    "stack": [
      "Java",
      "Spring Boot",
      "Gradle",
      "JPA",
      "MySQL",
      "Redis",
      "AWS S3/EC2",
      "Docker",
      "Jenkins",
      "Nginx",
      "Next.js",
      "React",
      "TypeScript",
      "PWA",
      "SSAFY 금융 API",
      "카카오 로그인"
    ],
    "lessons": [
      "외부 금융 API를 직접 연동하며 공통 헤더 생성, 사용자·단체별 키 관리, Redis 캐시 TTL 설계 등 호출 비용과 데이터 신선도의 균형을 고민했다.",
      "거래고유번호 같은 외부 시스템의 식별자를 내부 unique 키로 삼으면 반복 동기화에도 멱등성을 확보할 수 있다.",
      "예측과 신뢰지수처럼 단순하고 설명 가능한 모델을 선택해, 후원자에게 산정 기준을 그대로 공개하는 설계를 했다."
    ],
    "links": [
      {
        "label": "GitHub",
        "url": "https://github.com/YooSeungHo0124/YooHoo"
      }
    ],
    "pdf": {
      "href": "/pdfs/yoohoo.pdf",
      "label": "YooHoo 발표 자료",
      "pages": 27
    },
    "slides": [
      {
        "src": "/slides/yoohoo/p046.jpg",
        "caption": "문제 정의(엑셀·증빙 관리)와 세 가지 해결 방향"
      },
      {
        "src": "/slides/yoohoo/p048.jpg",
        "caption": "후원금 운용내역 요약과 카테고리별 비교 화면"
      },
      {
        "src": "/slides/yoohoo/p054.jpg",
        "caption": "Withdrawal 테이블의 transactionUniqueNo로 MySQL과 금융 API 거래를 연결"
      },
      {
        "src": "/slides/yoohoo/p058.jpg",
        "caption": "Spring이 Redis의 금융정보로 금융 API를 조회해 거래내역을 반환하는 흐름"
      },
      {
        "src": "/slides/yoohoo/p060.jpg",
        "caption": "신뢰지수 3가지 산정 기준(50/30/20점)"
      },
      {
        "src": "/slides/yoohoo/p061.jpg",
        "caption": "지수평활법 기반 후원금 수입·지출 예측 그래프"
      },
      {
        "src": "/slides/yoohoo/p067.jpg",
        "caption": "시스템 아키텍처(PWA, Nginx, Next.js, Spring Boot, MySQL, Redis, Jenkins, S3)"
      }
    ]
  },
  {
    "id": "albaro",
    "title": "AlBaro",
    "kicker": "SSAFY · DevOps",
    "period": "2025.01 — 2025.02",
    "role": "6인 팀(FE 2 · BE 3 · Infra 1) 중 인프라/DevOps 및 PM",
    "oneLiner": "알바 대타 구인 서비스의 배포 인프라를 전담해, GitLab push부터 EC2 운영 환경 반영까지 이어지는 이중 Docker Compose 기반 CI/CD 파이프라인을 구축했습니다.",
    "stats": [
      {
        "value": "약 7주",
        "label": "개발 기간"
      },
      {
        "value": "8개",
        "label": "운영 컨테이너 (Jenkins 1 + 앱 스택 7)"
      },
      {
        "value": "2개",
        "label": "Docker Compose 파일 (Jenkins용 / 앱 스택용)"
      },
      {
        "value": "1명",
        "label": "인프라 전담 인원 (팀 6인 중)"
      }
    ],
    "problem": "알바 현장에서는 결원이 생겨도 대타를 구하기 어렵습니다. 점장은 타지점 알바생에게, 알바생은 모르는 사람에게 개인적으로 연락해야 하는 부담이 있었습니다. AlBaro는 점주와 알바생 사이의 대타 요청, 지원, 채팅, QR 출석을 한 서비스로 묶은 프로젝트입니다. 제 과제는 프론트엔드(Next.js), 백엔드(Spring Boot), MySQL, Redis, 얼굴 인식 서비스(Flask)로 이루어진 다중 서비스를, 팀원이 develop 브랜치에 push하면 반영되는 배포 환경으로 만드는 것이었습니다. 인프라 경험이 없는 상태에서 시작해, EC2 생성과 보안 그룹부터 직접 조사하며 학습했습니다.",
    "approach": [
      {
        "title": "이중 Docker Compose로 CI 도구와 앱 스택 분리",
        "body": "루트 docker-compose.yml에는 Jenkins 컨테이너만, jenkins/docker-compose.yml에는 앱 스택(frontend, backend, MySQL, Redis, Nginx, certbot, face_recognition)을 정의했습니다. 파이프라인이 앱 스택을 down/up 해도 Jenkins 자신은 영향받지 않게 하려는 분리입니다. 대신 Jenkins가 호스트 Docker를 조작하도록 docker.sock을 마운트해야 했고, 이는 권한 범위가 넓어지는 트레이드오프입니다."
      },
      {
        "title": "Jenkins 커스텀 이미지",
        "body": "jenkins/jenkins:lts 위에 Docker CE와 docker-compose를 설치하고 jenkins 사용자를 docker 그룹에 추가한 이미지를 직접 정의했습니다. 컨테이너 안의 Jenkins가 빌드와 배포 명령을 실행할 수 있습니다."
      },
      {
        "title": "GitLab Webhook + Jenkinsfile 자동 배포",
        "body": "push가 GitLab Webhook으로 Jenkins에 전달되면 Checkout(develop), Build(gradlew build), .env 생성, 기존 컨테이너 down, up --build -d, Nginx 배포 순으로 진행되도록 stage를 구성했습니다. 프론트 키는 Jenkins Credentials로 주입해 저장소에 값이 남지 않게 했습니다."
      },
      {
        "title": "Nginx reverse proxy와 HTTPS",
        "body": "80 포트는 443으로 리다이렉트하고 Let's Encrypt 인증서를 적용했습니다. /api와 /ws는 backend, 얼굴 인식 경로는 Flask 서비스, 그 외는 Next.js frontend로 라우팅해 외부에는 단일 진입점만 노출했습니다."
      },
      {
        "title": "WebSocket 프록시 설정",
        "body": "실시간 채팅과 알림을 위해 /ws 경로에 Upgrade/Connection 헤더 처리, 3600초 read/send timeout, 버퍼링 해제를 설정했습니다."
      },
      {
        "title": "데이터 계층 분리와 기동 순서 제어",
        "body": "MySQL 8과 Redis를 각각 별도 컨테이너로 두고, backend에는 환경변수로 호스트를 주입했습니다. backend Dockerfile에서 wait-for-it.sh로 db:3306 준비를 기다린 뒤 기동하게 했습니다."
      },
      {
        "title": "포팅 메뉴얼 작성",
        "body": "서비스별 포트와 파이프라인 생성·배포 순서, 백업 대상(jenkins_home, MySQL 데이터, SSL 인증서)을 문서화해 다른 환경에서도 재현할 수 있게 했습니다."
      }
    ],
    "architecture": "Developer --push--> GitLab --Webhook--> Jenkins (container)\n                                              |\n                          Checkout > Build > .env > down > up --build\n                                              v\n  AWS EC2 (Docker)\n  +----------------------------------------------------------+\n  |  Nginx :80/:443 (Let's Encrypt, certbot renew 12h)       |\n  |    /        -> frontend  (Next.js :3000)                 |\n  |    /api     -> backend   (Spring Boot :8080)             |\n  |    /ws      -> backend   (WebSocket, Upgrade)            |\n  |    /flask/* -> face_recognition (Flask :5000)            |\n  |  backend --> MySQL 8 (:3306) , Redis (:6379)             |\n  +----------------------------------------------------------+\n  compose #1: Jenkins only / compose #2: app stack (7 services)",
    "challenges": [
      {
        "problem": "컨테이너 기동 순서: backend가 MySQL보다 먼저 떠서 연결에 실패할 수 있었습니다.",
        "solution": "backend Dockerfile에서 wait-for-it.sh로 db:3306이 열릴 때까지 대기한 뒤 애플리케이션을 시작하도록 했습니다.",
        "cause": "Compose의 컨테이너 시작 순서는 DB의 준비 완료를 보장하지 않습니다."
      },
      {
        "problem": "WebSocket 채팅이 Nginx reverse proxy를 거치면 연결 유지 설정이 필요했습니다.",
        "solution": "/ws 경로에 Upgrade/Connection 헤더 전달, 3600초 timeout, 버퍼링 해제를 적용했습니다.",
        "cause": "일반 HTTP 프록시 설정만으로는 WebSocket 업그레이드와 장시간 연결이 처리되지 않습니다."
      },
      {
        "problem": "HTTPS 인증서 만료로 서비스가 중단될 위험이 있었습니다.",
        "solution": "certbot 컨테이너가 12시간마다 renew를 실행하고 Nginx를 reload하는 루프를 구성했습니다.",
        "cause": "Let's Encrypt 인증서는 주기적인 갱신이 필요합니다."
      }
    ],
    "results": [
      {
        "metric": "배포 방식",
        "after": "GitLab push, Webhook, Jenkins 파이프라인으로 EC2 컨테이너 재배포",
        "condition": "Jenkinsfile 기준"
      },
      {
        "metric": "컨테이너 구성",
        "after": "Jenkins 1개, 앱 스택 7개 서비스",
        "condition": "docker-compose 기준"
      },
      {
        "metric": "외부 진입점",
        "after": "Nginx 80/443 단일 진입, HTTP는 HTTPS로 리다이렉트",
        "condition": "Nginx 설정 기준"
      },
      {
        "metric": "서비스 시연",
        "after": "실시간 채팅/알림(WebSocket), QR 출석, 반경 내 지점 리스트가 배포 환경에서 동작",
        "condition": "최종 발표 2025.02.21"
      },
      {
        "metric": "운영 문서",
        "after": "포팅 메뉴얼(서비스 포트, 파이프라인 순서, 백업 대상)",
        "condition": "산출물"
      },
      {
        "metric": "정량 성능 지표",
        "after": "배포 시간, 트래픽, 가용성 등은 측정하지 않았습니다.",
        "condition": "-"
      }
    ],
    "stack": [
      "AWS EC2",
      "Docker",
      "Docker Compose",
      "Jenkins",
      "GitLab Webhook",
      "Nginx",
      "Let's Encrypt / certbot",
      "MySQL 8",
      "Redis",
      "Spring Boot 3.4.1 (Java 17)",
      "Next.js",
      "Flask"
    ],
    "lessons": [
      "인프라 경험이 없는 상태에서 EC2 생성, EBS, 보안 그룹부터 스스로 조사하며 배포 환경을 끝까지 구축해 본 경험이 되었습니다.",
      "CI 도구와 앱 스택을 Compose 단위로 분리하면 재배포 시 영향 범위를 줄일 수 있지만, docker.sock 마운트처럼 권한 범위가 커지는 대가가 따른다는 점을 배웠습니다.",
      "WebSocket, 인증서 갱신, DB 준비 대기처럼 기능 코드에 드러나지 않는 운영 요소가 서비스 안정성에 직접 영향을 준다는 점을 체감했습니다."
    ],
    "links": [
      {
        "label": "GitHub",
        "url": "https://github.com/YooSeungHo0124/AlBaro"
      }
    ],
    "pdf": {
      "href": "/pdfs/albaro.pdf",
      "label": "AlBaro 발표 자료",
      "pages": 23
    },
    "slides": [
      {
        "src": "/slides/albaro/p073.jpg",
        "caption": "문제 정의: 알바 커뮤니티에서 대타를 구하지 못한 실제 게시글 캡처"
      },
      {
        "src": "/slides/albaro/p082.jpg",
        "caption": "문제 상황 3가지 요약(인원 부족, 타지점 요청 곤란, 개인 연락 부담)"
      },
      {
        "src": "/slides/albaro/p084.jpg",
        "caption": "서비스 로직: 점주>알바생, 알바생>알바생, 알바생>점주 세 가지 대타 흐름"
      },
      {
        "src": "/slides/albaro/p087.jpg",
        "caption": "알바생>점주 화면: 지도 기반 지점 목록으로 대타 근무 지원"
      },
      {
        "src": "/slides/albaro/p089.jpg",
        "caption": "서비스 확장성: 카카오톡 플러스 친구, QR 코드 출석"
      },
      {
        "src": "/slides/albaro/p091.jpg",
        "caption": "인프라 아키텍처: GitLab Webhook, Jenkins, EC2 위 Next/Nginx/Spring/Redis/MySQL Docker 구성"
      },
      {
        "src": "/slides/albaro/p092.jpg",
        "caption": "적용 기술: WebSocket 실시간 알림/채팅, QR 출석, 5KM 반경 지점 리스트"
      }
    ]
  },
  {
    "id": "tong",
    "title": "TONG",
    "kicker": "SSAFY · Full-stack",
    "period": "2024.10 — 2024.11",
    "role": "2인 팀 팀장 · 실시간 채팅, AI 챗봇 '통키', JWT·Kakao 로그인 담당",
    "oneLiner": "일반 회원과 운동 전문가(PT 쌤)를 지도 기반으로 매칭하고, 실시간 1:1 채팅과 AI 챗봇 마스코트 '통키'를 제공하는 웹 서비스.",
    "stats": [
      {
        "value": "31일",
        "label": "프로젝트 기간 (2024.10.28 ~ 11.27)"
      },
      {
        "value": "2인",
        "label": "팀 규모 (팀장 담당)"
      },
      {
        "value": "5개",
        "label": "핵심 기능 (사용자·커뮤니티·매칭·일정·채팅)"
      },
      {
        "value": "13개",
        "label": "MySQL 테이블"
      }
    ],
    "problem": "혼자서 신체·마음 건강을 관리하기는 어렵고, 자신의 목표에 맞는 전문가를 찾아 연결되는 과정도 번거롭습니다. 동기부여를 유지하려면 같은 목표를 가진 사람들과의 소통도 필요합니다. TONG은 이를 세 축으로 풀었습니다. AI 챗봇과의 대화(나와 나), 전문가를 직접 확인하고 신청하는 매칭(나와 너), 구성원이 함께 만드는 게시판(나와 우리)입니다. 저는 실시간 소통(채팅, 챗봇)과 인증(JWT, 소셜 로그인)을 맡았습니다.",
    "approach": [
      {
        "title": "STOMP over SockJS 기반 1:1 채팅",
        "body": "Spring 메시지 브로커(@EnableWebSocketMessageBroker)로 구독은 /topic, 발행은 /app으로 나눴습니다. 채팅방은 매칭 ID 단위(/topic/chat/{matchingId})입니다. 매칭이 수락되면 채팅방이 자동으로 열리는 도메인 흐름과 1:1로 대응되어 방 관리가 단순해집니다. 프론트는 Vue에서 @stomp/stompjs와 sockjs-client로 연결했습니다."
      },
      {
        "title": "연결 안정성 설정",
        "body": "heartbeat(서버 10s/10s, SockJS 25s), disconnect delay 5s, 전송 시간 30s, 버퍼 512KB, 메시지 128KB 제한을 두었습니다. 연결·종료·오류를 로깅하는 데코레이터도 추가했습니다."
      },
      {
        "title": "읽음 표시·안 읽은 수·채팅방 목록",
        "body": "메시지는 MyBatis로 저장하고 내역을 조회합니다. 읽음 처리는 단건과 일괄 두 경로를 두었고, 처리 후 READ 메시지를 브로드캐스트해 상대 화면의 읽음 표시를 갱신합니다. 안 읽은 수 조회, 채팅방 목록, 타이핑 이벤트도 구현했습니다. 화면은 라이트/다크 모드를 지원합니다."
      },
      {
        "title": "챗봇 '통키': 로컬 한국어 LLM + 페르소나 프롬프트",
        "body": "백엔드가 로컬 Ollama의 chat API를 호출합니다. 모델은 한국어 Llama-3 기반 8B GGUF(Q8_0) 공개 배포본입니다. 응답은 max_tokens 100, 비스트리밍으로 제한했습니다. 시스템 프롬프트로 당나귀 캐릭터 '통키'의 공손한 어투, '히히힝~', 간결한 답변, 부정적 내용의 긍정적 전환을 지정했습니다. 모델을 직접 학습하는 대신 프롬프트로 캐릭터를 제어해, 개발 기간 안에 동작하는 챗봇을 확보했습니다."
      },
      {
        "title": "JWT + Kakao OAuth2 인증",
        "body": "JWT(jjwt, 유효기간 1시간)에 이름·사용자 ID·회원 유형을 claim으로 담았습니다. 자체 회원가입·로그인과 별도로 Kakao 인가 코드를 토큰으로 교환해 사용자 정보를 조회하고, 로그아웃과 연결 끊기도 지원합니다. 프론트는 Pinia user store, jwt-decode, 라우터 가드로 로그인 상태와 접근을 제어했습니다."
      },
      {
        "title": "협업 방식",
        "body": "master(안정), develop(주 개발), 개인 브랜치 구조로 개발하고 develop에 PR로 병합했습니다. 프론트의 가입·로그인, 라우터, 메인 페이지, 시작 페이지도 함께 작업했습니다."
      }
    ],
    "architecture": "[Vue 3 + Vite + Vuetify + Pinia]\n   |  REST (Axios, JWT)     |  STOMP over SockJS\n   v                        v\n[Spring Boot 3.3.5 / Java 17]\n   |- user / jwt / oauth2 (Kakao)\n   |- chat (WebSocket broker: /app -> /topic/chat/{matchingId})\n   |- ai-chat --HTTP--> [Ollama: Korean Llama-3 8B GGUF]\n   |- board / expert / matching / reservation / quest / calendar\n   v\n[MySQL 8.0 (13 tables) via MyBatis]",
    "challenges": [
      {
        "problem": "챗봇용 한국어 모델을 직접 학습해 구동하려 했으나, 자체 모델을 Ollama에서 돌리지 못했습니다.",
        "solution": "공개 한국어 Llama-3 기반 GGUF 모델을 로컬 Ollama로 구동하고, 시스템 프롬프트로 '통키' 페르소나를 구현했습니다.",
        "result": "로컬에서 동작하는 한국어 페르소나 챗봇을 메인 화면에 연결했습니다. 응답 품질은 정량 측정하지 않았습니다."
      },
      {
        "problem": "실시간 채팅에서 상대방이 메시지를 읽었는지 화면에 반영해야 했습니다.",
        "solution": "읽음 처리 API 호출 뒤 READ 메시지를 같은 채팅방 토픽으로 브로드캐스트해, 상대 클라이언트가 읽음 표시를 갱신하도록 했습니다.",
        "result": "읽음 표시와 안 읽은 메시지 카운트가 동작합니다."
      }
    ],
    "results": [
      {
        "metric": "제 담당 구현 범위",
        "after": "WebSocket 1:1 채팅(읽음·안 읽은 수·채팅방 목록·타이핑), 챗봇 통키, JWT + Kakao OAuth2 로그인"
      },
      {
        "metric": "팀 전체 구현 범위",
        "after": "사용자 관리, 커뮤니티, 전문가 매칭(지도), 일정(예약·퀘스트), 실시간 채팅, AI 챗봇"
      },
      {
        "metric": "데이터 모델",
        "after": "MySQL 13개 테이블 (대댓글용 comment 자기참조 포함)"
      },
      {
        "metric": "챗봇 응답 제약",
        "after": "max_tokens 100, 비스트리밍, 로컬 Ollama 구동"
      },
      {
        "metric": "사용자 수·성능 지표",
        "after": "측정하지 않음"
      }
    ],
    "stack": [
      "Vue 3",
      "Vite",
      "Vuetify",
      "Pinia",
      "Axios",
      "SockJS / STOMP",
      "Spring Boot 3.3.5",
      "Java 17",
      "MyBatis",
      "MySQL 8.0",
      "JWT (jjwt)",
      "Kakao OAuth2",
      "Kakao Map API",
      "Ollama",
      "Llama-3 Korean 8B (GGUF)",
      "GitHub"
    ],
    "lessons": [
      "채팅방 단위를 도메인 키(매칭 ID)에 맞추니 방 생성·권한·구독 구조가 단순해졌습니다.",
      "연결 유지(heartbeat), 크기 제한, 로깅 같은 운영 설정은 실시간 기능에서 초기에 챙겨야 합니다.",
      "모델 직접 학습이 막혔을 때, 공개 모델과 프롬프트 설계로 범위를 좁힌 결정이 일정 안에 결과를 냈습니다.",
      "커밋 메시지가 비서술형이 많아 이력만으로 기여를 설명하기 어려웠습니다. 이후에는 서술형 메시지와 작은 단위 커밋을 씁니다."
    ],
    "pdf": {
      "href": "/pdfs/tong.pdf",
      "label": "TONG 발표 자료",
      "pages": 59
    },
    "slides": [
      {
        "src": "/slides/tong/p104.jpg",
        "caption": "기능명세서와 DB ERD 테이블 구성"
      },
      {
        "src": "/slides/tong/p107.jpg",
        "caption": "핵심 기능 5가지: 사용자 관리, 커뮤니티, 전문가 매칭, 일정 관리, 실시간 채팅"
      },
      {
        "src": "/slides/tong/p109.jpg",
        "caption": "메인 화면: 날씨, 일정, HOT 게시판, 챗봇 통키"
      },
      {
        "src": "/slides/tong/p127.jpg",
        "caption": "커뮤니티 설계: 자유 카테고리 + 찜/HOT 필터, 댓글·대댓글 테이블 구조"
      },
      {
        "src": "/slides/tong/p138.jpg",
        "caption": "카카오맵 기반 위치 전문가 리스트: 화면 영역 내 마커와 리스트 실시간 동기화(Map/Set)"
      },
      {
        "src": "/slides/tong/p152.jpg",
        "caption": "매칭 후 예약 신청과 퀘스트로 일정 관리하는 흐름"
      },
      {
        "src": "/slides/tong/p163.jpg",
        "caption": "챗봇 통키: 로컬 한국어 모델, 100 토큰 제한, 페르소나 시스템 프롬프트"
      }
    ]
  }
]
