#!/usr/bin/env python3
"""Build public PDFs / slide images / content modules for SSAFY + other projects.

Usage: python3 scripts/build-project-assets.py <work-dir>
  <work-dir>/screening.json : {id: {"pages":[a,b], "exclude":[{"page":n,"reason":..}], "key":[{"page":n,"caption":..}]}}
  <work-dir>/public/<id>.json : publish-ready project JSON
  <work-dir>/pdf/src.pdf     : the full source PDF

Outputs:
  public/pdfs/<id>.pdf           (source pages minus excluded pages, recompressed)
  public/slides/<id>/pNN.jpg     (selected key slides)
  data/ssafy-content.ts, data/projects-content.ts
Fails if any excluded page ended up in a key slide, or published text has blocked tokens.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

WORK = Path(sys.argv[1])
ROOT = Path(__file__).resolve().parent.parent
PUB = ROOT / 'public'
SRC = WORK / 'pdf' / 'src.pdf'

SSAFY = ['odab', 'yoohoo', 'albaro', 'tong']
OTHERS = ['vestella', 'kium', 'ict', 'astel']

TITLES_PDF = {
    'odab': 'O!dAb 발표 자료',
    'yoohoo': 'YooHoo 발표 자료',
    'albaro': 'AlBaro 발표 자료',
    'tong': 'TONG 발표 자료',
    'ict': 'ICT 교육 프로젝트 자료',
    'astel': 'X-ray rewindowing 자료',
}

BLOCK = re.compile(
    r'UNVERIFIED|CONFLICT|REDACTED|Notion|사실 파일|본인 커밋|이력서|초안|슬라이드 ?p\d|'
    r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b|ssh-|password|passwd|비밀번호|ghp_|sk-[A-Za-z0-9]{10}|'
    r'[\w.+-]+@[\w-]+\.[\w.]+',
    re.I,
)
_deny = Path(__file__).resolve().parent / 'denylist.local.txt'  # git-ignored: real names of people/customers
if _deny.exists():
    _words = [w.strip() for w in _deny.read_text().splitlines() if w.strip() and not w.startswith('#')]
    if _words:
        BLOCK = re.compile(BLOCK.pattern + '|' + '|'.join(re.escape(w) for w in _words), re.I)
KEEP = ('id', 'title', 'kicker', 'period', 'role', 'oneLiner', 'stats', 'problem', 'approach',
        'architecture', 'challenges', 'results', 'stack', 'lessons', 'links')


def run(cmd):
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def scan(o, path, bad):
    if isinstance(o, dict):
        for k, v in o.items():
            scan(v, f'{path}.{k}', bad)
    elif isinstance(o, list):
        for i, v in enumerate(o):
            scan(v, f'{path}[{i}]', bad)
    elif isinstance(o, str):
        m = BLOCK.search(o)
        if m:
            s = max(0, m.start() - 30)
            bad.append(f'{path}: …{o[s:m.end() + 30]}…'.replace('\n', ' '))


screening = json.loads((WORK / 'screening.json').read_text())
bad = []
data = {}

for pid in SSAFY + OTHERS:
    f = WORK / 'public' / f'{pid}.json'
    if not f.exists():
        print(f'skip {pid}: no public json')
        continue
    d = json.loads(f.read_text())
    d = {k: d[k] for k in KEEP if k in d and d[k] not in (None, '', [])}

    sc = screening.get(pid)
    if sc:
        excl = {e['page'] for e in sc.get('exclude', [])}
    if sc and sc.get('pages'):
        a, b = sc['pages']
        keep_pages = [p for p in range(a, b + 1) if p not in excl]
        # --- filtered PDF
        out = PUB / 'pdfs' / f'{pid}.pdf'
        out.parent.mkdir(parents=True, exist_ok=True)
        page_list = ','.join(str(p) for p in keep_pages)
        run(['gs', '-q', '-dNOPAUSE', '-dBATCH', '-sDEVICE=pdfwrite', '-dPDFSETTINGS=/ebook',
             f'-sPageList={page_list}', f'-sOutputFile={out}', str(SRC)])
        d['pdf'] = {'href': f'/pdfs/{pid}.pdf', 'label': TITLES_PDF.get(pid, '발표 자료 PDF'), 'pages': len(keep_pages)}
        print(f'{pid}: pdf {len(keep_pages)}/{b - a + 1} pages ({out.stat().st_size // 1024} KB), excluded {sorted(excl)}')
    if sc:
        slides = []
        for k in sc.get('key', []):
            pg = k['page']
            if pg in excl:
                print(f'!! {pid}: key page {pg} is excluded — skipped')
                continue
            sd = PUB / 'slides' / pid
            sd.mkdir(parents=True, exist_ok=True)
            base = sd / f'p{pg:03d}'
            run(['pdftoppm', '-f', str(pg), '-l', str(pg), '-jpeg', '-jpegopt', 'quality=78',
                 '-scale-to-x', '1280', '-scale-to-y', '-1', '-singlefile', str(SRC), str(base)])
            slides.append({'src': f'/slides/{pid}/p{pg:03d}.jpg', 'caption': k['caption']})
        if slides:
            d['slides'] = slides
        print(f'{pid}: key slides {len(slides)}')
    scan(d, pid, bad)
    data[pid] = d

if bad:
    print('BLOCKED — blocked tokens in published text:')
    print('\n'.join(bad))
    sys.exit(1)


def emit(name, ids, var):
    items = [data[i] for i in ids if i in data]
    ts = (
        "// AUTO-GENERATED by scripts/build-project-assets.py — edit the source JSON, not this file.\n"
        "import type { ProjectContent } from '@/components/ProjectDetail'\n\n"
        f"export const {var}: ProjectContent[] = {json.dumps(items, ensure_ascii=False, indent=2)}\n"
    )
    (ROOT / 'data' / name).write_text(ts)
    print(f'wrote data/{name} ({len(items)} items)')


emit('ssafy-content.ts', SSAFY, 'ssafyProjects')
emit('projects-content.ts', OTHERS, 'otherProjects')
