#!/usr/bin/env python3
"""Convert reviewed/public-edited project JSON into data/daton-content.ts.

Usage: python3 scripts/build-daton-content.py <dir-with-json>
Fails (exit 1) if any internal audit token is left in a published field.
"""
import json
import re
import sys
from pathlib import Path

SRC = Path(sys.argv[1])
OUT = Path(__file__).resolve().parent.parent / 'data' / 'daton-content.ts'

ORDER = [
    'cctv-system',
    'vlm-secondary',
    'translation-distill',
    'llm-router',
    'training-infra',
    'rt-film',
    'engineering-log',
]
OTHER = []

BLOCK = re.compile(
    r'UNVERIFIED|CONFLICT|REDACTED|\(Notion|Notion|사실 파일|shard|본인 커밋|이력서|초안|'
    r'tech[-_ ]?see|daton-|/home/|/data/|'
    r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b|ssh-|InternVL|Qwen',
    re.I,
)
_deny = Path(__file__).resolve().parent / 'denylist.local.txt'  # git-ignored: real customer names etc.
if _deny.exists():
    _words = [w.strip() for w in _deny.read_text().splitlines() if w.strip() and not w.startswith('#')]
    if _words:
        BLOCK = re.compile(BLOCK.pattern + '|' + '|'.join(re.escape(w) for w in _words), re.I)
KEEP = ('id', 'title', 'kicker', 'period', 'role', 'oneLiner', 'stats', 'problem', 'approach',
        'architecture', 'challenges', 'results', 'stack', 'lessons')


def scan(o, path, bad):
    if isinstance(o, dict):
        for k, v in o.items():
            scan(v, f'{path}.{k}', bad)
    elif isinstance(o, list):
        for i, v in enumerate(o):
            scan(v, f'{path}[{i}]', bad)
    elif isinstance(o, str):
        m = BLOCK.search(o)
        if m:
            s = max(0, m.start() - 30)
            bad.append(f'{path}: …{o[s:m.end() + 30]}…'.replace('\n', ' '))


def load(pid, bad):
    d = json.loads((SRC / f'{pid}.json').read_text())
    d = {k: d[k] for k in KEEP if k in d and d[k] not in (None, '', [])}
    scan(d, pid, bad)
    return d


bad = []
main = [load(p, bad) for p in ORDER if (SRC / f'{p}.json').exists()]
other = []
if bad:
    print('BLOCKED — internal/sensitive tokens remain:')
    print('\n'.join(bad))
    sys.exit(1)

ts = (
    "// AUTO-GENERATED by scripts/build-daton-content.py — edit the source JSON, not this file.\n"
    "import type { ProjectContent } from '@/components/ProjectDetail'\n\n"
    f"export const datonProjects: ProjectContent[] = {json.dumps(main, ensure_ascii=False, indent=2)}\n"
)
OUT.write_text(ts)
print(f'wrote {OUT} ({len(main)} daton projects)')
